services:
  postgres-jooq-16669:
    image: postgres:15.7-alpine
    command: postgres
    container_name: jooq-16669-postgres
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: jooq-16669-root
      POSTGRES_PASSWORD: jooq-16669-root
      POSTGRES_DB: jooq-16669-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
